### ISSUE TITLE
I want to know how the data you generate after preprocessing the information is introduced into the subsequent training process?

### ISSUE THREAD

**Issue by chaoyuan666** [moritzblum/literal_transformations#1]
I found that there are only operations on the data preprocessing part in GitHub repository, but the subsequent use seems to be the training code in LiteralE GitHub repository, which does not seem to involve the files generated after preprocessing in this GitHub repository. For example: FB15k-237_transformation_Literal2Entity.txt. Therefore, the preprocessed files do not seem to participate in subsequent training. How to improve performance?

**Comment by moritzblum** [comment]
Hi @chaoyuan666 , 
as described in our `README`, you should do the following:
1. place the created dataset folders in `LiteralE/data/'
2. modify and run the `preprocess.sh` (replace by our preprocessing script `LiteralE_mod/preprocess.sh`)
3. run the commands in LiteralE_mod/run.sh.

**Comment by chaoyuan666** [comment]
Hi @moritzblum ,
thank you for your reply. I saw the relevant process in the `README`. But what I want to know is when was the generated file FB15k-237_transformation_Literal2Entity.txt used by the model? When did it participate in model training?

**Comment by moritzblum** [comment]
Oh, I see. `FB15k-237_transformation_Literal2Entity.txt` must be concatenated with the original training file and placed as `train.txt` inside the `FB15k-237_transformation_[x]` directory. If I remember correctly, this is done in `setup.py` line 232 f.

**Comment by chaoyuan666** [comment]
OK, I see that. I didn't process these datasets all at once, so I didn't notice this file. Thanks again for your prompt reply.😂
